name: ci

on:
  - push

jobs:
  publish-npm:  
    name: Publish NPM Package
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'

      - name: Add GiHub Package Token
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Generate typescript type definition stuffs
        run:  cp -R scripts/typescript/. gen/typescript/

      - name: Set Variables
        id: vars
        run: |
          echo "::set-output name=github_short_sha::$(git rev-parse --short HEAD | cut -c1-7)"

      - name: Publish New Package with latest tag
        working-directory: gen/typescript
        run: |
          VERSION=$(TZ=Asia/Seoul date +'%Y.%m.%d-%H%M%S')-${{ steps.vars.outputs.github_short_sha }}
          npm version $VERSION --no-git-tag-version
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}